<a href="https://colab.research.google.com/github/rutik75/rutik75/blob/main/Internship.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import pandas as pd
import numpy as np

In [116]:
true = pd.read_csv('True.csv')

In [117]:
fake = pd.read_csv('Fake.csv')

In [118]:
true.head()

,title,content,label
0,Cabinet Approves Four Railway Projects Worth ₹...,The Union Cabinet approved four railway multi-...,1
1,ISRO announces launch window for Gaganyaan hum...,ISRO has confirmed the launch window for the a...,1

In [119]:
fake.head()

,title,content,label
0,Scientists discover a portal to another dimens...,Reports claim that researchers have discovered...,0
1,Government to provide every citizen with a fre...,"In a surprise move, the government announced t...",0

In [120]:
true['label']=1

In [121]:
fake['label']=0

In [122]:
true.head()

,title,content,label
0,Cabinet Approves Four Railway Projects Worth ₹...,The Union Cabinet approved four railway multi-...,1
1,ISRO announces launch window for Gaganyaan hum...,ISRO has confirmed the launch window for the a...,1

In [123]:
news = pd.concat([fake,true],axis=0)

In [31]:
news.head()

,title,text,subject,date,label
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0

In [32]:
news.tail()

,title,text,subject,date,label
21412,'Fully committed' NATO backs new U.S. approach...,BRUSSELS (Reuters) - NATO allies on Tuesday we...,worldnews,"August 22, 2017",1
21413,LexisNexis withdrew two products from Chinese ...,"LONDON (Reuters) - LexisNexis, a provider of l...",worldnews,"August 22, 2017",1
21414,Minsk cultural hub becomes haven from authorities,MINSK (Reuters) - In the shadow of disused Sov...,worldnews,"August 22, 2017",1
21415,Vatican upbeat on possibility of Pope Francis ...,MOSCOW (Reuters) - Vatican Secretary of State ...,worldnews,"August 22, 2017",1
21416,Indonesia to buy $1.14 billion worth of Russia...,JAKARTA (Reuters) - Indonesia will buy 11 Sukh...,worldnews,"August 22, 2017",1

In [33]:
news.isnull().sum()

title      0
text       0
subject    0
date       0
label      0
dtype: int64

In [34]:
news = news.drop(['title','subject','date'],axis=1)

In [35]:
news.head()

                                                text  label
0  Donald Trump just couldn t wish all Americans ...      0
1  House Intelligence Committee Chairman Devin Nu...      0
2  On Friday, it was revealed that former Milwauk...      0
3  On Christmas day, Donald Trump announced that ...      0
4  Pope Francis used his annual Christmas Day mes...      0

In [36]:
news = news.sample(frac=1)            #reshuffling

In [37]:
news.head()

                                                    text  label
4402   BERLIN (Reuters) - The U.S. military strike on...      1
20702  Hillary s over-the-top plan to tax the consume...      0
18360  This group of Black Lives Matter supporters ma...      0
10007  What the heck happened to our freedom of speec...      0
9346   (Reuters) - At least five animal rights activi...      1

In [38]:
news.reset_index(inplace=True)

In [39]:
news.head()

   index                                               text  label
0   4402  BERLIN (Reuters) - The U.S. military strike on...      1
1  20702  Hillary s over-the-top plan to tax the consume...      0
2  18360  This group of Black Lives Matter supporters ma...      0
3  10007  What the heck happened to our freedom of speec...      0
4   9346  (Reuters) - At least five animal rights activi...      1

In [40]:
news.drop(['index'],axis=1,inplace = True)

In [41]:
news.head()

                                                text  label
0  BERLIN (Reuters) - The U.S. military strike on...      1
1  Hillary s over-the-top plan to tax the consume...      0
2  This group of Black Lives Matter supporters ma...      0
3  What the heck happened to our freedom of speec...      0
4  (Reuters) - At least five animal rights activi...      1

In [42]:
import re

In [43]:
def wordopt(text):
    #Convert into lowercase
    text = text.lower()

    # Remove URLS
    text = re.sub(r'https?://\S+|www\.\S+','',text)

    # Remove HTML tags
    text = re.sub(r'<.*?>', '', text)

    # Remove punctuation
    text = re.sub(r'[^\w\s]', '', text)

    # Remove digits
    text = re.sub(r'\d', '', text)

    # Remove newline characters
    text = re.sub(r'\n', ' ', text)

    return text

In [44]:
news['text'] = news['text'].apply(wordopt)

In [45]:
news['text']

0        berlin reuters  the us military strike on a sy...
1        hillary s overthetop plan to tax the consumer ...
2        this group of black lives matter supporters ma...
3        what the heck happened to our freedom of speec...
4        reuters  at least five animal rights activists...
                               ...
44893    beirut reuters  fighters with the syrian kurdi...
44894    washington reuters  us senate democrats urged ...
44895    washington reuters  the white house said on tu...
44896    abuja reuters  more than  people have fled sou...
44897    former republican house intelligence cmte chai...
Name: text, Length: 44898, dtype: object

In [46]:
x = news['text']
y = news['label']

In [47]:
x

0        berlin reuters  the us military strike on a sy...
1        hillary s overthetop plan to tax the consumer ...
2        this group of black lives matter supporters ma...
3        what the heck happened to our freedom of speec...
4        reuters  at least five animal rights activists...
                               ...
44893    beirut reuters  fighters with the syrian kurdi...
44894    washington reuters  us senate democrats urged ...
44895    washington reuters  the white house said on tu...
44896    abuja reuters  more than  people have fled sou...
44897    former republican house intelligence cmte chai...
Name: text, Length: 44898, dtype: object

In [48]:
y

0        1
1        0
2        0
3        0
4        1
        ..
44893    1
44894    1
44895    1
44896    1
44897    0
Name: label, Length: 44898, dtype: int64

In [49]:
from sklearn.model_selection import train_test_split

In [50]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3)

In [51]:
x_train.shape

(31428,)

In [52]:
x_test.shape

(13470,)

In [53]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [54]:
vectorization = TfidfVectorizer()

In [55]:
xv_train = vectorization.fit_transform(x_train)

In [56]:
xv_test = vectorization.transform(x_test)

In [57]:
xv_train

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 6449148 stored elements and shape (31428, 175148)>

In [58]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

In [59]:
LR = LogisticRegression()

In [60]:
LR.fit(xv_train, y_train)

LogisticRegression()

In [61]:
pred_lr = LR.predict(xv_test)

In [62]:
LR.score(xv_test, y_test)

0.9892353377876764

In [63]:
print(classification_report(y_test, pred_lr))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      7087
           1       0.99      0.99      0.99      6383

    accuracy                           0.99     13470
   macro avg       0.99      0.99      0.99     13470
weighted avg       0.99      0.99      0.99     13470

In [64]:
from sklearn.tree import DecisionTreeClassifier

In [65]:
DTC = DecisionTreeClassifier()

In [66]:
DTC.fit(xv_train,y_train)

DecisionTreeClassifier()

In [67]:
pred_dtc = DTC.predict(xv_test)

In [68]:
DTC.score(xv_test, y_test)

0.9964365256124722

In [69]:
print(classification_report(y_test,pred_dtc))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      7087
           1       1.00      1.00      1.00      6383

    accuracy                           1.00     13470
   macro avg       1.00      1.00      1.00     13470
weighted avg       1.00      1.00      1.00     13470

In [70]:
from sklearn.ensemble import RandomForestClassifier

In [71]:
rfc = RandomForestClassifier()

In [72]:
rfc.fit(xv_train, y_train)

RandomForestClassifier()

In [73]:
predict_rfc = rfc.predict(xv_test)

In [74]:
rfc.score(xv_test, y_test)

0.9883444691907943

In [75]:
print(classification_report(y_test,predict_rfc))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      7087
           1       0.99      0.99      0.99      6383

    accuracy                           0.99     13470
   macro avg       0.99      0.99      0.99     13470
weighted avg       0.99      0.99      0.99     13470

In [1]:
from sklearn.ensemble import GradientBoostingClassifier

In [2]:
gbc = GradientBoostingClassifier()

In [76]:
gbc.fit(xv_train, y_train)

GradientBoostingClassifier()

In [80]:
pred_gbc = gbc.predict(xv_test)

In [81]:
gbc.score(xv_test, y_test)

0.9953971789161099

In [82]:
print(classification_report(y_test,pred_gbc))

              precision    recall  f1-score   support

           0       1.00      0.99      1.00      7087
           1       0.99      1.00      1.00      6383

    accuracy                           1.00     13470
   macro avg       1.00      1.00      1.00     13470
weighted avg       1.00      1.00      1.00     13470

In [97]:
def output_label(n):
    if n == 0:
        return "It is a Fake News"
    elif n == 1:
        return "It is a Genuine News"

In [101]:
def manual_testing(news):
    testing_news = {"text": [news]}  # create a DataFrame with the input text
    new_def_test = pd.DataFrame(testing_news)
    new_def_test["text"] = new_def_test["text"].apply(wordopt)  # preprocess
    new_x_test = new_def_test["text"]

    new_xv_test = vectorization.transform(new_x_test)  # vectorize the text

    pred_lr = LR.predict(new_xv_test)
    pred_gbc = gbc.predict(new_xv_test)
    pred_rfc = rfc.predict(new_xv_test)

    return "\n\nLR Prediction: {} \nGBC Prediction: {} \nRFC Prediction: {}".format(
        output_label(pred_lr[0]),
        output_label(pred_gbc[0]),
        output_label(pred_rfc[0])
    )

In [113]:
news_article = str(input())

India won a total of 107 medals, including 28 golds, at the 2023 Asian Games held in Hangzhou, China. This marked India's best-ever performance at the Asian Games, surpassing the previous record of 70 medals in 2018.

In [115]:
manual_testing(news_article)

'\n\nLR Prediction: It is a Fake News \nGBC Prediction: It is a Fake News \nRFC Prediction: It is a Fake News'